import { ENV } from "../config/env.js";

export const JWT_CONFIG = {
    JWT_ACCESS_SECRET: ENV.JWT_ACCESS_SECRET,
    JWT_ACCESS_EXPIRES_IN: ENV.JWT_ACCESS_EXPIRES_IN,
    JWT_REFRESH_SECRET: ENV.JWT_REFRESH_SECRET,
    JWT_REFRESH_EXPIRES_IN: ENV.JWT_REFRESH_EXPIRES_IN,
}