export const PERMISSIONS = {
    // Workspace
    MANAGE_WORKSPACE: "MANAGE_WORKSPACE",
    MANAGE_WORKSPACE_MEMBERS: "MANAGE_WORKSPACE_MEMBERS",
    VIEW_WORKSPACE_MEMBERS: "VIEW_WORKSPACE_MEMBERS",
    VIEW_WORKSPACE_PROJECTS: "VIEW_WORKSPACE_PROJECTS",

    // Project
    VIEW_PROJECT: "VIEW_PROJECT",
    VIEW_PROJECT_MEMBERS: "VIEW_PROJECT_MEMBERS",
    MANAGE_PROJECT_MEMBERS: "MANAGE_PROJECT_MEMBERS",

    VIEW_PROJECT: "VIEW_PROJECT",
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",

    // Tasks
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_OWN_TASK: "DELETE_OWN_TASK",
    DELETE_ANY_TASK: "DELETE_ANY_TASK",
};