import { WORKSPACE_ROLES } from "./workspaceRoles.js";
import { PROJECT_ROLES } from "./projectRoles.js";
import { PERMISSIONS } from "./permissions.js";

export const WORKSPACE_ROLE_PERMISSIONS = {
    [WORKSPACE_ROLES.OWNER]: [
        PERMISSIONS.VIEW_WORKSPACE_MEMBERS,
        PERMISSIONS.MANAGE_WORKSPACE,
        PERMISSIONS.MANAGE_WORKSPACE_MEMBERS,
        PERMISSIONS.CREATE_PROJECT,
        PERMISSIONS.UPDATE_PROJECT,
        PERMISSIONS.DELETE_PROJECT,
        PERMISSIONS.VIEW_PROJECT,
        PERMISSIONS.VIEW_WORKSPACE_PROJECTS,
        PERMISSIONS.VIEW_PROJECT_MEMBERS,
        PERMISSIONS.MANAGE_PROJECT_MEMBERS,
        PERMISSIONS.VIEW_ALL_PROJECT_TASKS,
        PERMISSIONS.VIEW_TASK,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_OWN_TASK,
        PERMISSIONS.DELETE_ANY_TASK,
    ],

    [WORKSPACE_ROLES.ADMIN]: [
        PERMISSIONS.VIEW_WORKSPACE_MEMBERS,
        PERMISSIONS.MANAGE_WORKSPACE_MEMBERS,
        PERMISSIONS.CREATE_PROJECT,
        PERMISSIONS.UPDATE_PROJECT,
        PERMISSIONS.DELETE_PROJECT,
        PERMISSIONS.VIEW_PROJECT,
        PERMISSIONS.VIEW_WORKSPACE_PROJECTS,
        PERMISSIONS.VIEW_PROJECT_MEMBERS,
        PERMISSIONS.MANAGE_PROJECT_MEMBERS,
        PERMISSIONS.VIEW_ALL_PROJECT_TASKS,
        PERMISSIONS.VIEW_TASK,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_OWN_TASK,
        PERMISSIONS.DELETE_ANY_TASK,
    ],

    [WORKSPACE_ROLES.MEMBER]: [
        PERMISSIONS.VIEW_WORKSPACE_MEMBERS,
        PERMISSIONS.VIEW_PROJECT,
        PERMISSIONS.VIEW_ALL_PROJECT_TASKS,
        PERMISSIONS.VIEW_TASK,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_OWN_TASK,
    ],
};

export const PROJECT_ROLE_PERMISSIONS = {
    [PROJECT_ROLES.PROJECT_ADMIN]: [
        PERMISSIONS.VIEW_PROJECT,
        PERMISSIONS.UPDATE_PROJECT,
        PERMISSIONS.VIEW_PROJECT_MEMBERS,
        PERMISSIONS.MANAGE_PROJECT_MEMBERS,
        PERMISSIONS.VIEW_ALL_PROJECT_TASKS,
        PERMISSIONS.VIEW_TASK,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_OWN_TASK,
        PERMISSIONS.DELETE_ANY_TASK,
    ],

    [PROJECT_ROLES.MEMBER]: [
        PERMISSIONS.VIEW_PROJECT,
        PERMISSIONS.VIEW_ALL_PROJECT_TASKS,
        PERMISSIONS.VIEW_TASK,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_OWN_TASK,
        PERMISSIONS.VIEW_PROJECT_MEMBERS,
    ],
};